version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
  reviewers:
  - valfirst
  - ikalinin1
  - uarlouski
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
  open-pull-requests-limit: 99
  reviewers:
  - valfirst
  - ikalinin1
  - uarlouski
